name: "units-test"
on:
  label:
    types: [created, deleted]

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test
    env: 
      TODO_TOKEN: ${{ secrets.TODO_TOKEN }}
